# Generated by Django 5.0.2 on 2024-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.CharField(max_length=300)),
                ('task_date', models.DateField(blank=True)),
            ],
        ),
    ]
