# Generated by Django 5.0.2 on 2024-02-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_description',
            field=models.CharField(blank=True, max_length=22),
        ),
    ]
