# Generated by Django 5.0.2 on 2024-02-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_tasks_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_description',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
